### ISSUE TITLE
Automatically add label to Bottlerocket nodes for agent scheduling

### ISSUE THREAD

**Issue by jahkeup** [bottlerocket-os/bottlerocket-update-operator#11]
**What I'd like:**

The update operator should automatically be eligible for scheduling on to Bottlerocket hosts in a Kubernetes cluster. 

The suggested deployment uses a label to identify Bottlerocket hosts and schedule on them (ie: the `bottlerocket.aws/platform-version` label. Name may change: #4). Instead of requiring the label to be set by administrators, the label could be set (or determined) automatically for Bottlerocket nodes to eliminate the manual step.

**Comment by rothgar** [comment]
The nodegroup can have labels applied to instances automatically to avoid needing to do it manually.

example eksctl config
```
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket2
  region: us-west-2
  version: '1.17'

nodeGroups:
  - name: ng-bottlerocket2
    labels: { bottlerocket.aws/updater-interface-version: 2.0.0 }
    instanceType: m5.large
    desiredCapacity: 3
    amiFamily: Bottlerocket
```
