### ISSUE TITLE
Bottlerocket update-operator-controller, Status "Pending", nodes didn't match node selector

### ISSUE THREAD

**Issue by ghost** [bottlerocket-os/bottlerocket-update-operator#34]
**Image I'm using:**
Cluster config derived from https://github.com/bottlerocket-os/bottlerocket/blob/develop/sample-eksctl.yaml
```

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clustername
  region: eu-central-1
  version: "1.16"

vpc:
  id: vpc-asdf
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  securityGroup: sg-asdf
  sharedNodeSecurityGroup: sg-asdf
  subnets:
    private:
      eu-central-1a: { id: subnet-asdf}
      eu-central-1b: { id: subnet-asfd}
      eu-central-1c: { id: subnet-asdf}
    public:
      eu-central-1a: { id: subnet-asdf}
      eu-central-1b: { id: subnet-asdf}
      eu-central-1c: { id: subnet-asdf}

nodeGroups:
  - name: spot-group-bottlerocket
    labels:
      role: spot-worker
      spotfleet: "yes"
    minSize: 1
    desiredCapacity: 1
    **amiFamily: Bottlerocket**
    maxSize: 10
    availabilityZones:
    - eu-central-1a
    privateNetworking: true
    volumeEncrypted: true
    volumeType: gp2
    volumeSize: 50
    instancesDistribution:
      instanceTypes:
      - m5a.large
      - m5.large
      - m5d.large
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
    securityGroups:
      attachIDs:
      - sg-asdf
      withLocal: false
      withShared: true
    iam:
      attachPolicyARNs:
      - arn:aws:iam::asdf
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
    tags:
      Projekt: EKS
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/clustername: owned
      bottlerocket.aws/updater-interface-version: 1
```

Flux custom template derived from https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/update-operator.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: bottlerocket
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bottlerocket-update-operator-controller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  # Allow the controller to remove Pods running on the Nodes that are updating.
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bottlerocket-update-operator-controller
subjects:
  - kind: ServiceAccount
    name: update-operator-controller
    namespace: bottlerocket
roleRef:
  kind: ClusterRole
  name: bottlerocket-update-operator-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bottlerocket-update-operator-agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bottlerocket-update-operator-agent
subjects:
  - kind: ServiceAccount
    name: update-operator-agent
    namespace: bottlerocket
roleRef:
  kind: ClusterRole
  name: bottlerocket-update-operator-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-operator-controller
  namespace: bottlerocket
  annotations:
    kubernetes.io/service-account.name: update-operator-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-operator-agent
  namespace: bottlerocket
  annotations:
    kubernetes.io/service-account.name: update-operator-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-operator-controller
  namespace: bottlerocket
  labels:
    update-operator: controller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      update-operator: controller
  template:
    metadata:
      namespace: bottlerocket
      labels:
        update-operator: controller
    spec:
      serviceAccountName: update-operator-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bottlerocket.aws/updater-interface-version
                    operator: Exists
                  - key: "kubernetes.io/os"
                    operator: In
                    values:
                      - linux
                  - key: "kubernetes.io/arch"
                    operator: In
                    values:
                      - amd64
        # Avoid update-operator's Agent Pods if possible.
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                topologyKey: bottlerocket.aws/updater-interface-version
                labelSelector:
                  matchExpressions:
                    - key: update-operator
                      operator: In
                      values: ["agent"]
      containers:
      - name: controller
        image: "asdf.amazonaws.com/bottlerocket-update-operator:v0.1.3"
        imagePullPolicy: Always
        args:
          - -controller
          - -debug
          - -nodeName
          - $(NODE_NAME)
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: update-operator-agent
  namespace: bottlerocket
  labels:
    update-operator: agent
spec:
  selector:
    matchLabels:
      update-operator: agent
  template:
    metadata:
      labels:
        update-operator: agent
    spec:
      serviceAccountName: update-operator-agent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: bottlerocket.aws/updater-interface-version
                    operator: Exists
                  - key: "kubernetes.io/os"
                    operator: In
                    values:
                      - linux
                  - key: "kubernetes.io/arch"
                    operator: In
                    values:
                      - amd64
      hostPID: true
      containers:
        - name: agent
          image: "asdf.amazonaws.com/bottlerocket-update-operator:v0.1.3"
          imagePullPolicy: Always
          # XXX: tty required to exec binaries that use `simplelog` until https://github.com/bottlerocket-os/bottlerocket/issues/576 is resolved.
          tty: true
          args:
            - -agent
            - -debug
            - -nodeName
            - $(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            # Required for executing OS update operations.
            privileged: true
          resources:
            limits:
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 600Mi
          volumeMounts:
            - name: rootfs
              mountPath: /.bottlerocket/rootfs
      volumes:
        - name: rootfs
          hostPath:
            path: /
            type: Directory
```

**What I expected to happen:**
update operator controller should be added to cluster and should be running

**What actually happened:**
update operator controller was added to cluster and never scheduled.

```
Pod
   Type     Reason             Age                   From                Message                                                                                           │
│   ----     ------             ----                  ----                -------                                                                                           │
│   Normal   NotTriggerScaleUp  3m37s (x61 over 13m)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 3 node(s) didn't match node │
│  selector                                                                                                                                                                 │
│   Warning  FailedScheduling   44s (x11 over 13m)    default-scheduler   0/3 nodes are available: 3 node(s) didn't match node selector.   

Node-Selectors:  <none>    
│ Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s                                                                                                          │
│                  node.kubernetes.io/unreachable:NoExecute for 300s 

Node
│ Taints:             <none>    
```

**How to reproduce the problem:**
Set up an EKS Cluster v 1.16, use files like those above. Pod ist not scheduled.

**Comment by etungsten** [comment]
Currently the update operator deployment schedules the pods only on nodes with the label `bottlerocket.aws/updater-interface-version=1.0.0`. 

I see that you were trying to add this label via `tags` for the `spot-group-bottlerocket` nodegroup in the `ClusterConfig` which tags the EC2 node instances. The appropriate field for adding kubernetes labels should be `labels`. Like so,
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
...
nodeGroups:
  - name: spot-group-bottlerocket
    labels:
      role: spot-worker
      spotfleet: "yes"
      bottlerocket.aws/updater-interface-version: "1.0.0"
...
```

To add this label to all the nodes in your existing EKS cluster, you can do the following:
```
kubectl label node $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}') bottlerocket.aws/updater-interface-version=1.0.0
```
     
Or if you want to target specific nodes for the update operator:
```
kubectl label node $NODE_NAME bottlerocket.aws/updater-interface-version=1.0.0
```
