### ISSUE TITLE
Error when `SCHEDULER_CRON_EXPRESSION` is set without `UPDATE_WINDOW_START` & `UPDATE_WINDOW_STOP`

### ISSUE THREAD

**Issue by prashant-prodigal** [bottlerocket-os/bottlerocket-update-operator#428]
We are installing bottlerocket update operator in an EKS with no internet access. But the operator deployment starts failing, its giving this error:

  2023-03-09T13:12:28.369373Z  INFO actix_server::builder: starting 2 workers
    at /src/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.2.0/src/builder.rs:200

  2023-03-09T13:12:28.369436Z ERROR controller: controller exited
    at controller/src/main.rs:110

I am using Latest image as per the docs. Could you pls point me to what could be wrong here?

**Comment by jpmcb** [comment]
Hi @prashant-prodigal - the error you are seeing at `controller/src/main.rs:110` is related to the controller's metric server attempting to bind to the local loopback network and start serving metrics.

> We are installing bottlerocket update operator in an EKS with no internet access.

Note that the Bottlerocket update operator requires network access to `updates.bottlerocket.aws`: this is how update operator system queries for new OS updates. Read more about it here: https://github.com/bottlerocket-os/bottlerocket-update-operator#why-are-my-bottlerocket-nodes-egressing-to-httpsupdatesbottlerocketaws

Does your node have some network attached? In order for the prometheus server to come up, it'll at least need to be able to bind on `0.0.0.0` for IPv4 clusters or `[::]` for IPv6 clusters.

Can you provide the full logs from the failed controller deployment?

```
 kubectl logs -n brupop-bottlerocket-aws pod/brupop-controller-deployment-{YOUR-DEPLOYMENT}
```

**Comment by prashant-prodigal** [comment]
Hello, I have allowed the URL https://updates.bottlerocket.aws still we are getting below error from command
 kubectl logs -n brupop-bottlerocket-aws pod/brupop-controller-deployment-{YOUR-DEPLOYMENT}

  2023-03-10T04:36:28.369259Z  INFO actix_server::builder: starting 2 workers
    at /src/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.2.0/src/builder.rs:200

  2023-03-10T04:36:28.369368Z ERROR controller: controller exited
    at controller/src/main.rs:110

**Comment by jpmcb** [comment]
What's the shape of your network? Are there any other logs in from the other update operator components?

**Comment by blakeromano** [comment]
I am seeing the same thing when my node has access to egress.

```
brupop-controller-deployment-875956b84-l42nf   0/1     CrashLoopBackOff   7 (2m32s ago)   13m
```
```
2023-04-11T20:56:31.570124Z  INFO actix_server::builder: starting 1 workers
at /src/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.2.0/src/builder.rs:200
2023-04-11T20:56:31.570208Z ERROR controller: controller exited
at controller/src/main.rs:110
```
With the deployment like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: brupop-controller-deployment
  namespace: brupop-bottlerocket-aws
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: brupop-controller
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        brupop.bottlerocket.aws/component: brupop-controller
      namespace: brupop-bottlerocket-aws
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - command:
        - ./controller
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SCHEDULER_CRON_EXPRESSION
          value: '* * * * * * *'
        - name: MAX_CONCURRENT_UPDATE
          value: "1"
        image: public.ecr.aws/bottlerocket/bottlerocket-update-operator:v1.1.0
        imagePullPolicy: IfNotPresent
        name: brupop
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 3m
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      priorityClassName: brupop-controller-high-priority
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: brupop-controller-service-account
      serviceAccountName: brupop-controller-service-account
      terminationGracePeriodSeconds: 30
```
