### ISSUE TITLE
Incorrect agent resources requests

### ISSUE THREAD

**Issue by gthao313** [bottlerocket-os/bottlerocket-update-operator#485]
We updated agent resources requests to `cpu: 5m memory: 8Mi`, but on current manifest we still use old numbers. we should fix it

[agent resource limits from chart(develop branch](https://github.com/bottlerocket-os/bottlerocket-update-operator/blob/develop/deploy/charts/bottlerocket-update-operator/templates/agent-daemonset.yaml#L54-L59)):
```
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
```
[agent resource limits from manifest:](https://raw.githubusercontent.com/bottlerocket-os/bottlerocket-update-operator/1.1.0/yamlgen/deploy/bottlerocket-update-operator.yaml)
```
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 8Mi
```
