### ISSUE TITLE
Splunk otel-collector needs the brupop-controller-deployment pods annotated

### ISSUE THREAD

**Issue by AndreiBanaruTakeda** [bottlerocket-os/bottlerocket-update-operator#676]
**Image I'm using:**
v1.3.0

**Issue or Feature Request:**
In order for the Splunk otel-collector to scrape the metrics from the `brupop-controller-deployment` pods, the pods need to be annotated:
```yaml
prometheus.io/port: "8080"
prometheus.io/scrape: "true"
```

I see `service/brupop-controller-server` is annotated with the above, but [Splunk looks for those annotations at the pod level](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#additional-telemetry-sources).

Proposal is to add the annotations in the `deployment/brupop-controller-deployment`:
```yaml
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
```

**Testing executed:**
1. I manually edited `deploy/brupop-controller-deployment` and added the above annotations
2. ```kubectl rollout restart deployment brupop-controller-deployment```
3. I had to wait for the `scheduler_cron_expression` for metrics to become available
4. Checked for the metrics in Splunk
