### ISSUE TITLE
Brupop-agent has high throttled cpu

### ISSUE THREAD

**Issue by Matthieulvt** [bottlerocket-os/bottlerocket-update-operator#726]
Hi ! 

We are trying to monitor better what happens on our kubernetes Cluster. We are using brupop-update-operator 1.4.0 and we notice despite setting up higher cpu & memory requests, the brupop-agent is getting quite high CPU throttled. 

Here's some metrics about our sizing in requests (for brupop-agent):

<img width="946" alt="Image" src="https://github.com/user-attachments/assets/5fecadf6-a65a-448c-835d-2bd6cd92842e" />

Which seems nicely adapted, but when we are looking to the `container.cpu_throttled` metrics, our cluster have a constant 100ms throttled for brupop-agent :

<img width="462" alt="Image" src="https://github.com/user-attachments/assets/5ee565b9-7b4c-4c3e-ad6a-85cb4add0ca5" />

We are using the following parameters when deploying the chart regarding resources :

```yaml
    exclude_from_lb_wait_time_in_sec: "3O"
    scheduler_cron_expression: "${var.brupop_scheduler_cron_expression}"
    resources:
      agent:
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 20Mi
      apiserver:
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 40Mi
      controller:
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 60Mi
```

We already bumped the resources from what's recommanded in the README.md :
> The `bottlerocket-update-operator.yaml` manifest makes several default recommendations for
Kubernetes resource requests and limits. In general, the update operator and its components are lite-weight
and shouldn't consume more than 10m CPU (which is roughly equivalent to 1/100th of a CPU core)
and 50Mi (which is roughly equivalent to 0.05 GB of memory).
If this limit is breached, the Kubernetes API will restart the faulting container.

In this scenario should I double the limits for brupop-agent to avoid constant throttle period, even if cpu usage seems ok ?

**Issue or Feature Request:** High CPU Throttled for brupop-agent / Adapt documentation regarding resources allocation
